### ISSUE TITLE
`wget` doesn't exist on all systems

### ISSUE THREAD

**Issue by transcental** [Tarcaxoxide/Sauce#3]
I use macOS Catalina 10.15.7, and `wget` isn't a command. As far as I know, curl is universal/more common, so maybe migrate to curl?

*Error:*
```zsh
dillonbarnes at Downstairs-iMac in ~/Sauce on Master
± make setup 
mkdir -p Compiler/src/
wget --continue "https://ftp.gnu.org/gnu/binutils/binutils-2.37.tar.xz" -O Compiler/src/binutils-2.37.tar.xz
/bin/sh: wget: command not found
make: *** [Compiler/src/binutils-2.37.tar.xz] Error 127
```

Or, you could add a note in README.md saying for users on macOS, they need to install `wget` via homebrew: `brew install wget`

**Comment by Tarcaxoxide** [comment]
oh uhmmm ok thanks. i'm not running mac so i couldn't know that sorry.
I'll see about converting that into a curl command instead.

**Comment by Tarcaxoxide** [comment]
switched to curl.

looking into testing clang to see if that compiles my project. if it does then this fix was pointless.
